version: '3'

networks:
  mysql-net:
    external:
      name: ${MYSQL_DOCKER_NETWORK}

services:
  nginx:
    build: ./nginx/
    container_name: hargadunia-nginx
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
    - ./www/:/var/www/html
    environment:
      - VIRTUAL_HOST=${HOSTNAME}
    networks:
      - mysql-net
    restart: always
  php:
    build: ./php/
    container_name: hargadunia-php
    expose:
      - 9000
    volumes:
      - ./www/:/var/www/html
    networks:
      - mysql-net
    restart: always