version: '3'

services:
  nginx:
    build: ./nginx/
    container_name: hargadunia-nginx
    ports:
      - 80
    depends_on:
      - php
    volumes:
    - ./www/:/var/www/html
    networks:
      mysql-net:
        ipv4_address: ${NGINX_IP}
    restart: unless-stopped
  php:
    build: ./php/
    container_name: hargadunia-php
    expose:
      - 9000
    volumes:
      - ./www/:/var/www/html
    networks:
      mysql-net:
        ipv4_address: ${PHP_IP}
    restart: unless-stopped

networks:
  mysql-net:
    external:
      name: ${MYSQL_DOCKER_NETWORK}