version: '3'

services:
  nginx:
    build: ./nginx/
    ports:
      - 8080
    depends_on:
      - php
    volumes:
    - ./www/:/var/www/html
    environment:
      - VIRTUAL_HOST=${HOSTNAME}
  php:
    build: ./php/
    expose:
      - 9000
    depends_on:
      - mysql
      # - memcached
    volumes:
      - ./www/:/var/www/html
  mysql:
    image: mariadb:latest
    ports:
      - 3306
    volumes:
      - /var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    ports:
     - 2112:2112
    environment:
      PMA_HOST: mysql
      VIRTUAL_HOST: ${PHPMYADMIN_HOST}
  # memcached:
  #   image: memcached:latest
  #   ports:
  #     - 11211:11211
  #   restart: always
  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"
  
  # elasticsearch:
  # image: elasticsearch
  # ports:
  #   - "9200:9200"
  #   - "9300:9300"

  # rabbitmq:
  #   image: rabbitmq:3.6.1-management
  #   ports:
  #     - "15672:15672"
  #     - "5672:5672"
  
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro